#pragma kernel CSMain




cbuffer CB{
    int chunkID;
    int2 dispatchSize;
}; 
#include "MeshProperties.hlsl"


StructuredBuffer<uint> _IndirectArgs;

RWStructuredBuffer<MeshProperties> _Grass;


// For the sake of simplicity, only using 1, 1, 1 threads.
//lol no
[numthreads(THREADGROUPS,1,1)]
void CSMain (uint3 id : SV_DispatchThreadID) {

    uint index = id.x;

    if (_Grass[index].chunkID == chunkID){
        _Grass[index] = (MeshProperties)0;
    }
}